# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android Build

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a tag matching the pattern v*.*.* is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload GodotAndroidBle artifact
        uses: actions/upload-artifact@v4
        with:
          name: godotandroidble-release-aar
          path: app/build/outputs/aar/GodotAndroidBle-release.aar

      - name: Upload Blessed artifact
        uses: actions/upload-artifact@v4
        with:
          name: blessed-release-aar
          path: blessed/build/outputs/aar/blessed-release.aar

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5 # Check out the repository code

      - name: Download GodotAndroidBle artifact
        uses: actions/download-artifact@v5
        with:
          name: godotandroidble-release-aar
          path: artifacts/bin/release

      - name: Download Blessed artifact
        uses: actions/download-artifact@v5
        with:
          name: blessed-release-aar
          path: artifacts/bin/release

      - name: Copy export scripts and zip artifacts
        shell: bash
        run: |
          cp export_scripts/plugin.cfg artifacts/
          cp export_scripts/export_plugin.gd artifacts/
          cd artifacts
          zip -r GodotAndroidBle.zip plugin.cfg export_plugin.gd bin/release/GodotAndroidBle-release.aar bin/release/blessed-release.aar

      - name: Create release
        id: create_release
        uses: actions/create-release@v1 # Create a GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate using GitHub token
        with:
          tag_name: ${{ github.ref }} # Use the pushed tag name
          release_name: Release ${{ github.ref }} # Use the pushed tag name as the release name
          body_path: RELEASE_NOTES.md # Path to the release notes file
          # body: |
          #   Changes in this Release
          #   - First Change
          #   - Second Change # Release notes
          draft: false # Whether it's a draft
          prerelease: false # Whether it's a prerelease

      - name: Upload final artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate using GitHub token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Use the upload URL generated by the create release step
          asset_path: artifacts/GodotAndroidBle.zip # Path of the file to upload
          asset_name: GodotAndroidBle.zip # Name of the file to upload
          asset_content_type: application/zip # File content type
