# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android Build

on:
  workflow_call:
    inputs:
      godot_version:
        required: false
        type: string
        default: '4.4.1'
      use_matrix:
        required: false
        type: boolean
        default: false

jobs:
  matrix-setup:
    uses: ./.github/workflows/matrix-setup.yml

  build:
    runs-on: ubuntu-latest
    needs: matrix-setup
    strategy:
      matrix:
        include: ${{ inputs.use_matrix && fromJson(needs.matrix-setup.outputs.version-matrix) || fromJson(format('[{{"godot":"{0}","kotlin":"1.9.22"}}]', inputs.godot_version)) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup godot-lib
        run: |
          mkdir -p godot-lib
          filename="godot-lib.${{ matrix.godot }}.stable.template_release.aar"
          echo "configurations.maybeCreate(\"default\")" > godot-lib/build.gradle
          echo "artifacts.add(\"default\", file('$filename'))" >> godot-lib/build.gradle
          url="https://github.com/godotengine/godot/releases/download/${{ matrix.godot }}-stable/${filename}"
          curl -L -o "godot-lib/${filename}" "$url"

      - name: Build with Gradle
        run: ./gradlew build -Pkotlin_version=${{ matrix.kotlin }}

      - name: Rename AAR for release
        run: |
          mv app/build/outputs/aar/GodotAndroidBle-release.aar GodotAndroidBle-godot-${{ matrix.godot }}-release.aar
          mv blessed/build/outputs/aar/blessed-release.aar blessed-godot-${{ matrix.godot }}-release.aar

      - name: Upload GodotAndroidBle artifact
        uses: actions/upload-artifact@v4
        with:
          name: godotandroidble-${{ matrix.godot }}
          path: app/build/outputs/aar/GodotAndroidBle-godot-${{ matrix.godot }}-release.aar

      - name: Upload Blessed artifact
        uses: actions/upload-artifact@v4
        with:
          name: blessed-${{ matrix.godot }}
          path: blessed/build/outputs/aar/blessed-godot-${{ matrix.godot }}-release.aar
