# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android Build

on:
  workflow_call:
    inputs:
      godot_version:
        required: false
        type: string
        default: '4.4.1'
      use_matrix:
        required: false
        type: boolean
        default: false
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a tag matching the pattern v*.*.* is pushed

jobs:
  matrix-setup:
    uses: ./.github/workflows/matrix-setup.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup godot-lib
        run: |
          mkdir -p godot-lib
          filename="godot-lib.${{ matrix.godot }}.stable.template_release.aar"
          echo "configurations.maybeCreate(\"default\")" > godot-lib/build.gradle
          echo "artifacts.add(\"default\", file('$filename'))" >> godot-lib/build.gradle
          url="https://github.com/godotengine/godot/releases/download/${{ matrix.godot }}-stable/${filename}"
          curl -L -o "godot-lib/${filename}" "$url"

      - name: Build with Gradle
        run: ./gradlew build -Pkotlin_version=${{ matrix.kotlin }}

      - name: Rename AAR for release
        run: |
          mv app/build/outputs/aar/GodotAndroidBle-release.aar GodotAndroidBle-godot-${{ matrix.godot }}-release.aar
          mv app/build/outputs/aar/blessed-release.aar blessed-godot-${{ matrix.godot }}-release.aar

      - name: Upload GodotAndroidBle artifact
        uses: actions/upload-artifact@v4
        with:
          name: godotandroidble-${{ matrix.godot }}
          path: app/build/outputs/aar/GodotAndroidBle-godot-${{ matrix.godot }}-release.aar

      - name: Upload Blessed artifact
        uses: actions/upload-artifact@v4
        with:
          name: blessed-${{ matrix.godot }}
          path: blessed/build/outputs/aar/blessed-godot-${{ matrix.godot }}-release.aar

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5 # Check out the repository code

      - name: Download GodotAndroidBle artifact
        uses: actions/download-artifact@v5
        with:
          name: godotandroidble-${{ matrix.godot }}
          path: artifacts/bin/release

      - name: Download Blessed artifact
        uses: actions/download-artifact@v5
        with:
          name: blessed-${{ matrix.godot }}
          path: artifacts/bin/release

      - name: Copy export scripts and zip artifacts
        shell: bash
        run: |
          cp export_scripts/plugin.cfg artifacts/
          cp export_scripts/export_plugin.gd artifacts/
          cd artifacts
          mv GodotAndroidBle-godot-${{ matrix.godot }}-release.aar bin/release/GodotAndroidBle-release.aar
          mv blessed-godot-${{ matrix.godot }}-release.aar bin/release/blessed-release.aar
          zip -r GodotAndroidBle-${{ matrix.godot }}.zip plugin.cfg export_plugin.gd bin/release/GodotAndroidBle-release.aar bin/release/blessed-release.aar

      - name: Create release
        id: create_release
        uses: actions/create-release@v1 # Create a GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate using GitHub token
        with:
          tag_name: ${{ github.ref }} # Use the pushed tag name
          release_name: Release ${{ github.ref }} # Use the pushed tag name as the release name
          body_path: RELEASE_NOTES.md # Path to the release notes file
          # body: |
          #   Changes in this Release
          #   - First Change
          #   - Second Change # Release notes
          draft: false # Whether it's a draft
          prerelease: false # Whether it's a prerelease

      - name: Upload final artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate using GitHub token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Use the upload URL generated by the create release step
          asset_path: artifacts/GodotAndroidBle-${{ matrix.godot }}.zip # Path of the file to upload
          asset_name: GodotAndroidBle-${{ matrix.godot }}.zip # Name of the file to upload
          asset_content_type: application/zip # File content type
