name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'

jobs:
  matrix-setup:
    uses: ./.github/workflows/matrix-setup.yml

  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      use_matrix: true

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build, matrix-setup]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5 # Check out the repository code

      - name: Download GodotAndroidBle artifact
        uses: actions/download-artifact@v5
        with:
          name: godotandroidble-${{ matrix.godot }}
          path: artifacts/bin/release

      - name: Download Blessed artifact
        uses: actions/download-artifact@v5
        with:
          name: blessed-${{ matrix.godot }}
          path: artifacts/bin/release

      - name: Copy export scripts and zip artifacts
        shell: bash
        run: |
          cp export_scripts/plugin.cfg artifacts/
          cp export_scripts/export_plugin.gd artifacts/
          cd artifacts
          mv GodotAndroidBle-godot-${{ matrix.godot }}-release.aar bin/release/GodotAndroidBle-release.aar
          mv blessed-godot-${{ matrix.godot }}-release.aar bin/release/blessed-release.aar
          zip -r GodotAndroidBle-${{ matrix.godot }}.zip plugin.cfg export_plugin.gd bin/release/GodotAndroidBle-release.aar bin/release/blessed-release.aar

      - name: Create release
        id: create_release
        uses: actions/create-release@v1 # Create a GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate using GitHub token
        with:
          tag_name: ${{ github.ref }} # Use the pushed tag name
          release_name: Release ${{ github.ref }} # Use the pushed tag name as the release name
          body_path: RELEASE_NOTES.md # Path to the release notes file
          # body: |
          #   Changes in this Release
          #   - First Change
          #   - Second Change # Release notes
          draft: false # Whether it's a draft
          prerelease: false # Whether it's a prerelease

      - name: Upload final artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate using GitHub token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Use the upload URL generated by the create release step
          asset_path: artifacts/GodotAndroidBle-${{ matrix.godot }}.zip # Path of the file to upload
          asset_name: GodotAndroidBle-${{ matrix.godot }}.zip # Name of the file to upload
          asset_content_type: application/zip # File content type
